apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pv-claim-jenkins
    labels: 
         app: webapp
spec:
    accessModes:
     -  ReadWriteOnce
    resources:
        requests:
           storage: 1Gi
